apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-home
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: [MY-IMAGE-NAME]
        ports:
        - containerPort: 80