name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./menu/pom.xml
          mvn clean package -f ./sales/pom.xml
          mvn clean package -f ./kitchen/pom.xml
          mvn clean package -f ./table/pom.xml
          mvn clean package -f ./customercenter/pom.xml

      - name: Docker Build and push for Menu
        uses: docker/build-push-action@v4
        with:
          context: ./menu
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/menu:latest
            ghcr.io/${{ github.repository }}/menu:${{ github.ref_name }}
            
      - name: Docker Build and push for Sales
        uses: docker/build-push-action@v4
        with:
          context: ./sales
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sales:latest
            ghcr.io/${{ github.repository }}/sales:${{ github.ref_name }}
            
      - name: Docker Build and push for Kitchen
        uses: docker/build-push-action@v4
        with:
          context: ./kitchen
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/kitchen:latest
            ghcr.io/${{ github.repository }}/kitchen:${{ github.ref_name }}
            
      - name: Docker Build and push for Table
        uses: docker/build-push-action@v4
        with:
          context: ./table
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/table:latest
            ghcr.io/${{ github.repository }}/table:${{ github.ref_name }}
            
      - name: Docker Build and push for Customercenter
        uses: docker/build-push-action@v4
        with:
          context: ./customercenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customercenter:latest
            ghcr.io/${{ github.repository }}/customercenter:${{ github.ref_name }}
            
